### ISSUE TITLE
github3.py

### ISSUE THREAD

**Issue by sjas** [sjas/.ansible#55]
needed still or obsolete?

**Comment by sjas** [comment]
possibly related:

```
# # currently: 1.2.6
# - name: get jsonfui version from github release
#   github_release:
#     user: AdrianSchneider
#     repo: jsonfui
#     action: latest_release
#   tags: github

- name: deploy jsonfui
  become: true
  become_user: sjas
  copy:
    src: jsonfui
    dest: /home/sjas/.local/bin
    mode: 0775
```
